# Generated by Django 5.1.4 on 2024-12-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_socialmedia_link_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_home',
            field=models.BooleanField(default=True),
        ),
    ]
